services:
  postgres:
    container_name: postgres
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
    - 5532:5432
    healthcheck:
      test: "pg_isready -U postgres"
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: "redis:5-alpine"
    ports:
      - 6479:6379
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      timeout: 3s
      retries: 30

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: src.settings.development
    volumes:
      - ./backend:/app
    ports:
      - 8100:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3100:3000
    depends_on:
      - backend
