
name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  tests:
    name: Test locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_TOKEN }}

      - name: Docker compose BUILD
        env:
          SERVICE_POSTGRES_PASSWORD: postgres
          SERVICE_POSTGRES_DATA_LOC: .
          SERVICE_POSTGRES_PORT: 5003
          SERVICE_REDIS_PORT: 5002
          SERVICE_BACKEND_PORT: 5001
          SERVICE_FRONTEND_ARG_REACT_APP_BACKEND_WEBSOCKET_URL: ws://localhost:4001/ws/
          SERVICE_FRONTEND_ARG_REACT_APP_BACKEND_API_URL: http://localhost:4001/api
          SERVICE_FRONTEND_PORT: 5000
        run: docker-compose -f docker-compose.production.yml build

      - name: Docker compose UP
        env:
          SERVICE_POSTGRES_PASSWORD: postgres
          SERVICE_POSTGRES_DATA_LOC: .
          SERVICE_POSTGRES_PORT: 5003
          SERVICE_REDIS_PORT: 5002
          SERVICE_BACKEND_PORT: 5001
          SERVICE_FRONTEND_ARG_REACT_APP_BACKEND_WEBSOCKET_URL: ws://localhost:4001/ws/
          SERVICE_FRONTEND_ARG_REACT_APP_BACKEND_API_URL: http://localhost:4001/api
          SERVICE_FRONTEND_PORT: 5000
        run: docker-compose -f docker-compose.production.yml up -d
