
name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  tests:
    name: Test locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_TOKEN }}

      - name: Docker compose BUILD
        run: docker-compose -f docker-compose.production.yml build

      - name: Docker compose UP
        run: docker-compose -f docker-compose.production.yml up -d

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_VPS_HOST }}
          username: ${{ secrets.PRODUCTION_VPS_USERNAME }}
          key: ${{ secrets.PRODUCTION_VPS_KEY }}
          command_timeout: 30m
          script: |
            cd chat-app
            git pull origin master
            git submodule update --recursive --remote
            docker-compose -f docker-compose.production.yml stop
            docker system prune --force
            docker-compose -f docker-compose.production.yml build
            docker-compose -f docker-compose.production.yml up -d