
name: Docker CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker compose build
        run: docker-compose --file docker-compose.production.yml build --no-cache

      - name: Docker compose up
        run: docker-compose --file docker-compose.production.yml up --force-recreate -d
